name: Build Android APK

on:
  push:
    branches:
      - main  # يقوم بالتفعيل عند دفع التغييرات إلى الفرع الرئيسي

jobs:
  build:
    runs-on: ubuntu-latest  # سيعمل على بيئة Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # يقوم بسحب الكود من المستودع

      - name: Set up JDK
        uses: actions/setup-java@v2  # يقوم بتثبيت JDK
        with:
          distribution: 'temurin'
          java-version: '11'  # تأكد من أن النسخة تتوافق مع بيئة مشروعك

      - name: Build APK
        run: ./gradlew assembleRelease  # بناء APK باستخدام Gradle

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3  # استخدام النسخة الأحدث v3
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk  # المسار إلى ملف APK الناتج
