name: Build Android APK

on:
  push:
    branches:
      - main  # يعمل فقط عندما تقوم بدفع التغييرات إلى الفرع 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # البيئة التي سيتم العمل عليها (Ubuntu)

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # يقوم بسحب الكود من المستودع

      - name: Set up JDK
        uses: actions/setup-java@v2  # يقوم بتثبيت JDK
        with:
          distribution: 'temurin'
          java-version: '11'  # تأكد من أنك تستخدم نفس النسخة التي تستخدمها في بيئة المشروع

      - name: Build APK
        run: ./gradlew assembleRelease  # يقوم ببناء APK من خلال Gradle

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3  # تم تحديث النسخة إلى v3
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk  # المسار إلى ملف APK الناتج
